config/routes.rb
SampleApp::Application.routes.draw do
  resources :sessions, :only => [:new, :create, :destroy]
 resources :users
 match '/about',   to: 'pages#about',   via: 'get'
 match '/contact', to: 'pages#contact', via: 'get'
 match '/signup', to: 'users#new', via: 'get'
 match '/help', to: 'pages#help', via: 'get'
 match '/signin', to:  'sessions#new', via: 'get'
 match '/signout', to: 'sessions#destroy', via: 'delete'
 
 root :to => "pages#home"

end

app/models/user.rb
class User < ActiveRecord::Base
	
	validates :name,  :presence => true, 
					  :length => {:maximum => 50}
	validates :email, :presence => true,
					  :uniqueness => {:case_sensitive => false}
				
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  @title = "Home"
  end

  def contact
  @title = "Contact"
  end
  
  def about
  @title = "About"
  end
  
  def help
  @title = "Help"
  end
  
  

 end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
	@title = "Sign in"
  end
  
  def create
	render 'new'
  end
  
  def destroy
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
	@user  = User.new
	@title = "Sign up"
  end
  
  def show
	@user = User.find(params[:id])
  end
  
  def create
	#raise params[:user].inspect
	@user = User.new(user_params)
	
      if @user.save
        
		redirect_to @user, :flash => {:success => "Welcome to the Sample App!"}
		#format.html { redirect_to @user, notice: 'User was successfully created.' }
        #format.json { render action: 'show', status: :created, location: @user }
      else
        @title = "Sign up"
		render 'new'
		#format.html { render action: 'new' }
        #format.json { render json: @user.errors, status: :unprocessable_entity }
      end
   
  end
  
  def user_params
	params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
def title
	base_title = "Ruby on Rails Tutorial Sample App"
	if @title.nil?
		base_title
	else
		"#{base_title} | #{@title}"
	end
 end
 
 def logo
	image_tag("logo.png", :alt => "Sample App", :class => "round")
 end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>

			<nav class ="round">
			<ul>
				<li><%= link_to "About", about_path %></li>
				<li><%= link_to "Contact", contact_path %></li>
				<li><%= link_to "News", '#' %></li>
				<li><%= link_to "Rails Tutorial", '#' %></li>
			</ul>
			</nav>
</footer>

app/views/layouts/_header.html.erb
<header>
			<%= link_to logo, root_path %>
			<nav class ="round">
			<ul>
				<li><%= link_to "Home", root_path %></li>
				<li><%= link_to "Help", help_path %></li>
				<li><%= link_to "Sign in", signin_path %></li>
			</ul>
			</nav>
		</header>

app/views/layouts/_stylesheets.html.erb
<%=  stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%=  stylesheet_link_tag 'blueprint/print', :media => 'print' %>
<%=  stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= title %></title>
<%= csrf_meta_tag %>
<%= render 'layouts/stylesheets' %>
</head>
<body>
	<div class = "container">
		<%= render '/layouts/header' %>
		<section class="round">
		<% flash.each do |key, value| %>
		<div class= "flash <%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
		</section>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>
</body>

app/views/pages/help.html.erb
<h1>Sample App</h1>
<p>Find me in app/views/pages/home.html.erb</p>
</body>
<%= link_to "Sign up now!", '#', :class => "signup_button round" %>

app/views/pages/home.html.erb
<h1>Sample App</h1>
<p>Find me in app/views/pages/home.html.erb</p>
</body>
<%= link_to "Sign up now!", signup_path, :class => "signup_button round" %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= form_for(@user) do |f| %>
<div class="field">
<%= f.label :name %>
<%= f.text_field :name %>

<br>
<%= f.label :email %>
<%= f.text_field :email %>

</div>
<div class="actions">
	<%= f.submit "Sign up" %>
</div>
<% end %>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>